np_rules = {
    ('CD', 'JJ', 'NN'),
    ('CD', 'NN'),
    ('CD', 'RB', 'JJ', 'NN'),
    ('DT', 'CD', 'JJ', 'NN'),
    ('DT', 'CD', 'NN'),
    ('DT', 'CD', 'RB', 'JJ', 'NN'),
    ('DT', 'JJ', 'CD', 'JJ', 'NN'),
    ('DT', 'JJ', 'CD', 'NN'),
    ('DT', 'JJ', 'CD', 'RB', 'JJ', 'NN'),
    ('DT', 'JJ', 'JJ', 'NN'),
    ('DT', 'JJ', 'NN'),
    ('DT', 'JJ', 'RB', 'JJ', 'NN'),
    ('DT', 'NN'),
    ('DT', 'RB', 'JJ', 'NN'),
    ('DT', 'RB', 'VB', 'NN'),
    ('DT', 'VB', 'NN'),
    ('JJ', 'CD', 'JJ', 'NN'),
    ('JJ', 'CD', 'NN'),
    ('JJ', 'CD', 'RB', 'JJ', 'NN'),
    ('JJ', 'JJ', 'NN'),
    ('JJ', 'NN'),
    ('JJ', 'RB', 'JJ', 'NN'),
    ('NN',)
}
